# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getListLength <- function(file) {
    .Call('largeList_getListLength', PACKAGE = 'largeList', file)
}

getListName <- function(file) {
    .Call('largeList_getListName', PACKAGE = 'largeList', file)
}

readList <- function(file, index = NULL) {
    .Call('largeList_readList', PACKAGE = 'largeList', file, index)
}

removeFromList <- function(file, index) {
    .Call('largeList_removeFromList', PACKAGE = 'largeList', file, index)
}

saveList <- function(object, file, append = FALSE) {
    .Call('largeList_saveList', PACKAGE = 'largeList', object, file, append)
}

