// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// readLargeList
RcppExport SEXP readLargeList(SEXP fileName, SEXP index);
RcppExport SEXP largeList_readLargeList(SEXP fileNameSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type fileName(fileNameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type index(indexSEXP);
    __result = Rcpp::wrap(readLargeList(fileName, index));
    return __result;
END_RCPP
}
// saveLargeList
RcppExport SEXP saveLargeList(SEXP object, SEXP fileName, SEXP append);
RcppExport SEXP largeList_saveLargeList(SEXP objectSEXP, SEXP fileNameSEXP, SEXP appendSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type object(objectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fileName(fileNameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type append(appendSEXP);
    __result = Rcpp::wrap(saveLargeList(object, fileName, append));
    return __result;
END_RCPP
}
