// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getListLength
RcppExport SEXP getListLength(SEXP file);
RcppExport SEXP largeList_getListLength(SEXP fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type file(fileSEXP);
    __result = Rcpp::wrap(getListLength(file));
    return __result;
END_RCPP
}
// getListName
RcppExport SEXP getListName(SEXP file);
RcppExport SEXP largeList_getListName(SEXP fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type file(fileSEXP);
    __result = Rcpp::wrap(getListName(file));
    return __result;
END_RCPP
}
// readList
RcppExport SEXP readList(SEXP file, SEXP index);
RcppExport SEXP largeList_readList(SEXP fileSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type file(fileSEXP);
    Rcpp::traits::input_parameter< SEXP >::type index(indexSEXP);
    __result = Rcpp::wrap(readList(file, index));
    return __result;
END_RCPP
}
// removeFromList
RcppExport SEXP removeFromList(SEXP file, SEXP index);
RcppExport SEXP largeList_removeFromList(SEXP fileSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type file(fileSEXP);
    Rcpp::traits::input_parameter< SEXP >::type index(indexSEXP);
    __result = Rcpp::wrap(removeFromList(file, index));
    return __result;
END_RCPP
}
// saveList
RcppExport SEXP saveList(SEXP object, SEXP file, SEXP append);
RcppExport SEXP largeList_saveList(SEXP objectSEXP, SEXP fileSEXP, SEXP appendSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type object(objectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type file(fileSEXP);
    Rcpp::traits::input_parameter< SEXP >::type append(appendSEXP);
    __result = Rcpp::wrap(saveList(object, file, append));
    return __result;
END_RCPP
}
